### ISSUE TITLE
The wrong favicon is displayed

### ISSUE THREAD

**Issue by admorris** [abmorris/firefox-cds-search#1]
When installing from [this page](https://addons.mozilla.org/en-GB/firefox/addon/cds-search/), the favicon of the Mozilla Addons website is shown instead of the file pointed to by the `<Image>` tag.

![sc](https://user-images.githubusercontent.com/15155249/34073479-08e99930-e29b-11e7-81bf-ba734b9c634e.png)

**Comment by iwansmith** [comment]
![image](https://user-images.githubusercontent.com/12726986/39119269-583d4976-46e3-11e8-8d25-1d34365c1bfd.png)

It looks fine with Firefox 59.0.2

**Comment by admorris** [comment]
Interesting. How did you install it, and which version were you using at the time?

**Comment by iwansmith** [comment]
Installed from https://addons.mozilla.org/en-US/firefox/addon/cds-search/ and used the version from 16th of December

**Comment by admorris** [comment]
I uninstalled, restarted FF and re-installed. The icon is now correct. Closing issue.
